### ISSUE TITLE
Practica 6_Reconocimiento de Imágenes

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-fugaz#2]
[Practica 6_Reconocimiento de Imágenes.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-fugaz/files/8597554/Practica.6_Reconocimiento.de.Imagenes.pdf)

**Comment by EMMANUELRHZ** [comment]
Calificación=20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
